/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#FFFEF0',
          100: '#FFFACC',
          200: '#FFF599',
          300: '#FFED66',
          400: '#FFE433',
          500: '#FFD700',
          600: '#CCB000',
          700: '#998400',
          800: '#665800',
          900: '#332C00',
        },
        secondary: {
          50: '#E8E8EC',
          100: '#D1D1D9',
          200: '#A3A3B3',
          300: '#75758D',
          400: '#474767',
          500: '#1a1a2e',
          600: '#151525',
          700: '#10101C',
          800: '#0B0B13',
          900: '#05050A',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.secondary.700'),
            '--tw-prose-headings': theme('colors.secondary.500'),
            '--tw-prose-links': theme('colors.primary.600'),
            '--tw-prose-bold': theme('colors.secondary.500'),
            '--tw-prose-counters': theme('colors.secondary.500'),
            '--tw-prose-bullets': theme('colors.primary.500'),
            '--tw-prose-hr': theme('colors.secondary.200'),
            '--tw-prose-quotes': theme('colors.secondary.500'),
            '--tw-prose-quote-borders': theme('colors.primary.500'),
            '--tw-prose-captions': theme('colors.secondary.400'),
            '--tw-prose-code': theme('colors.secondary.500'),
            '--tw-prose-pre-code': theme('colors.secondary.100'),
            '--tw-prose-pre-bg': theme('colors.secondary.500'),
            '--tw-prose-th-borders': theme('colors.secondary.200'),
            '--tw-prose-td-borders': theme('colors.secondary.100'),
            '--tw-prose-invert-body': theme('colors.secondary.200'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-links': theme('colors.primary.400'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.secondary.200'),
            '--tw-prose-invert-bullets': theme('colors.primary.500'),
            '--tw-prose-invert-hr': theme('colors.secondary.600'),
            '--tw-prose-invert-quotes': theme('colors.secondary.100'),
            '--tw-prose-invert-quote-borders': theme('colors.primary.500'),
            '--tw-prose-invert-captions': theme('colors.secondary.400'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.secondary.200'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.secondary.500'),
            '--tw-prose-invert-td-borders': theme('colors.secondary.600'),
            a: {
              textDecoration: 'none',
              '&:hover': {
                textDecoration: 'underline',
              },
            },
            h1: { fontWeight: '700' },
            h2: { fontWeight: '600' },
            h3: { fontWeight: '600' },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
